server:
  port: 8081

spring:
  application:
    name: post-service

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    consumer:
      group-id: post-service-group

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cassandra:
    keyspace-name: glowsky
    contact-points: ${CASSANDRA_HOST:localhost}
    port: ${CASSANDRA_PORT:9042}
    schema-action: CREATE_IF_NOT_EXISTS
    local-datacenter: datacenter1

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: true

opentracing:
  jaeger:
    service-name: post-service
    udp-sender:
      host: ${JAEGER_HOST:localhost}
      port: ${JAEGER_PORT:6831}
    sampler:
      type: const
      param: 1